language: cpp

os: linux

install:
    - sudo apt-get install gcc
    - sudo apt-get install cppcheck

script:
    - g++ greet.cpp -o greet.exe
    - ./greet.exe
    - cppcheck --error-exitcode=1 greet.cpp
