language: cpp

os: linux

install:
    - sudo apt-get install gcc
    - sudo apt-get install cppcheck

script:
    - "g++ -coverage *.cpp -o greet.exe"
    - ./greet.exe
    - cppcheck --error-exitcode=1 greet.cpp
    - gcov greet.cpp

after_success:
    - bash <(curl -s https://codecov.io/bash)
